name: htop
version: 2.0.1
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

apps:
  htop:
    command: usr/bin/htop

grade: stable
confinement: devmode # some stuff seems to require devmode

parts:
  htop:
    plugin: nil
    stage-packages:
      - htop
